name: Sync to Upstream

on:
  schedule:
    - cron:  '12 7 * * 1,4'
    # scheduled at 07:12 every Monday and Thursday
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync HEAD with upstream latest

    steps:
    - name: Checkout HEAD
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Pull upstream changes
      id: sync
      uses: bdougie/Fork-Sync-With-Upstream-action@fork
      with:
        upstream_repository: Bhuvnquo/visits-counter-docker
        upstream_branch: main
        target_branch: main                       # optional
        # merge_method: 
        git_config_pull_rebase: false
        # upstream_pull_args: --ff-only
        github_token: ${{ secrets.TOKEN }}   # optional, for accessing repos that require authentication
