name: Sync to Upstream

on:
  schedule:
    - cron:  '*/50 * * * *'
    # scheduled every 5 min
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Sync and merge upstream repository with your current repository
      uses: dabreadman/sync-upstream-repo@v1.3.0
      with:
        upstream_repo: https://github.com/Bhuvnquo/visits-counter-docker
        upstream_branch: main
        downstream_branch: main
        token: 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

